{{- range $serviceName, $serviceDefinition := .Values.services }}
{{- if and ( eq ( default true $serviceDefinition.enabled ) true ) $serviceDefinition.service }}
---
apiVersion: v1
kind: Service
metadata:
{{- if hasKey $serviceDefinition.service "name" }}
  name: {{ $serviceDefinition.service.name }}
{{- else }}
  name: {{ include "common.fullname" ( dict "root" $ "service" $serviceDefinition "serviceName" $serviceName ) }}
{{- end }}
{{- $svcDict := deepCopy $serviceDefinition }}
{{- $svcDict := merge $svcDict (dict "annotations" $serviceDefinition.service.annotations "labels" $serviceDefinition.service.labels) }}
{{- include "common.metadata" ( dict "root" $ "service" $svcDict "serviceName" $serviceName ) | nindent 2 }}
spec:
  type: {{ $serviceDefinition.service.type | default "ClusterIP" }}
  {{- with $serviceDefinition.service.ports }}
  ports:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  selector: {{- include "common.selectorLabels" ( dict "root" $ "service" $serviceDefinition "serviceName" $serviceName ) | nindent 4 }}
{{- end }}
{{- end }}
